apiVersion: v1
kind: Service
metadata:
  name: backend-despachos-service
spec:
  type: ClusterIP
  selector:
    app: backend-despachos-pod
  ports:
    - port: 8081
      targetPort: 8081

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-despachos-pod
  template:
    metadata:
      labels:
        app: backend-despachos-pod
    spec:
      containers:
        - name: backend-despachos-cont
          image: 179885810108.dkr.ecr.us-east-1.amazonaws.com/backend_despacho
          imagePullPolicy: Always
          ports:
            - containerPort: 8081