apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend-tienda-pod
  ports:
    - port: 8006
      targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-tienda-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-tienda-pod
  template:
    metadata:
      labels:
        app: frontend-tienda-pod
    spec:
      containers:
        - name: frontend-tienda-cont
          image: 179885810108.dkr.ecr.us-east-1.amazonaws.com/frontend_ventas
          imagePullPolicy: Always
          ports:
            - containerPort: 8080