name: CI/CD Pipeline - Innovatech despacho

on:
  push:
    branches:
      - main
    paths:
      - 'proyecto semestral/back-Despachos_SpringBoot/**'
permissions:
  id-token: write
  contents: read

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        
        cd "proyecto semestral/back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO"
        docker build -t backend-despacho .
        docker tag backend-despacho:latest ${{ secrets.ECR_REPOSITORY_DESPACHO }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_DESPACHO }}:latest

