name: CI/CD Pipeline - Innovatech ventas

on:
  push:
    branches:
      - main
    paths:
      - 'proyecto semestral/back-Ventas_SpringBoot/**'
permissions:
  id-token: write
  contents: read

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Backend y push a ECR
      run: |
        
        cd "proyecto semestral/back-Ventas_SpringBoot/Springboot-API-REST"
        docker build -t backend-ventas .
        docker tag backend-ventas:latest ${{ secrets.ECR_REPOSITORY_VENTAS }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_VENTAS }}:latest
    - name: Instalar kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: v1.29.0

    - name: Configurar kubeconfig para EKS
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME
        kubectl config current-context

    - name: despliegue a EKS
      env:
          EKS_NAMESPACE: ${{ secrets.EKS_NAMESPACE }}
      run: |
        kubectl apply -f k8s/backend-ventas-deployment.yaml -n $EKS_NAMESPACE
    - name: EKS comprobacion
      env:
          EKS_NAMESPACE: ${{ secrets.EKS_NAMESPACE }}
      run: |
        kubectl get pods -n $EKS_NAMESPACE
